### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by mo-paralenz** [zodern/mup-cloud-front#2]
Same issue as [mup-aws-beanstalk #104](https://github.com/zodern/mup-aws-beanstalk/issues/104)
Running mup 1.5.1

Configuration mup.js
```
module.exports = {
	servers: {
		one: {
			host: HOSTIP,
			username: HOSTUSER,
			pem:  #PEMPATH
		}
	},
	app: {
		name: APPNAME,
		path: '../',
		servers: {
			one: {},
		},
		buildOptions: {
			serverOnly: true,
		},
		env: {
			ROOT_URL: ROOTURL,
			MONGO_URL: 'mongodb://mongodb/meteor',
			MONGO_OPLOG_URL: 'mongodb://mongodb/local',
			// MONGO_OPLOG_URL: 'mongodb://mongodb/local',
		},

		docker: {
			image: 'abernix/meteord:node-12.16.1-base',
			prepareBundle: true,
			stopAppDuringPrepareBundle: false,
		},
		enableUploadProgressBar: true
	},

	mongo: {
		version: '3.4.1',
		servers: {
			one: {}
		}
	},

	proxy: {
		domains: LISTDOMAINS,
		ssl: {
			// Enable Let's Encrypt
			letsEncryptEmail: XXXXXXXXXXXX,
			forceSSL: true,
		},
	},

	cloudFront: {
		bucketName: BUCKETNAME,
		auth: {
			id: XXXXXXXXXXXXXXXXX,
			secret: XXXXXXXXXXXXX
		}
	},

	plugins: [
		'mup-cloud-front'
	]
};
```

Output
```
Unable to load plugin mup-cloud-front
ReferenceError: regeneratorRuntime is not defined
    at ********/node_modules/mup-cloud-front/lib/command-handlers.js:9:46
    at Object.<anonymous> (**********/node_modules/mup-cloud-front/lib/command-handlers.js:49:2)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (************/node_modules/mup-cloud-front/lib/commands.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
loaded config from *******/mup-dev/mup.js

1 Validation Error
  - "cloudFront" is an unknown property
```

**Comment by zodern** [comment]
I published version 0.2.2 with the fix.
